// frontend/src/components/BacklogPanel.vue
<script setup lang="ts">
import type { Message } from '@/types'

defineProps<{
  isOpen: boolean
  messages: Message[]
}>()

const emit = defineEmits<{ (e: 'close'): void }>()
</script>

<template>
  <Teleport to="body">
    <Transition name="backlog-slide">
      <div
        v-if="isOpen"
        class="fixed inset-0 z-30"
        style="background:rgba(0,0,0,0.5);"
        @click="emit('close')"
      >
        <!-- Panel slides in from right -->
        <div
          class="galgame-panel absolute top-0 right-0 bottom-0 flex flex-col"
          style="width:340px;max-width:90vw;"
          @click.stop
        >
          <!-- Header -->
          <div
            class="flex items-center justify-between font-ui flex-shrink-0"
            style="padding:16px 20px;border-bottom:1px solid rgba(255,215,0,0.15);"
          >
            <span style="color:#ffd700;font-size:14px;letter-spacing:3px;">📖 回 忆 录</span>
            <button
              style="color:rgba(255,255,255,0.5);cursor:pointer;"
              @click="emit('close')"
            >✕</button>
          </div>

          <!-- Messages -->
          <div
            class="flex-1 overflow-y-auto galgame-scrollbar"
            style="padding:16px 20px;"
          >
            <template v-if="messages.length === 0">
              <div style="color:rgba(255,255,255,0.3);font-size:13px;text-align:center;margin-top:40px;">
                暂无对话记录
              </div>
            </template>
            <div
              v-for="msg in messages"
              :key="msg.id"
              style="margin-bottom:16px;"
            >
              <div
                class="font-ui"
                :style="{
                  fontSize: '11px',
                  letterSpacing: '1px',
                  marginBottom: '4px',
                  color: msg.sender_type === 'user'
                    ? 'rgba(255,215,0,0.7)'
                    : 'rgba(167,139,250,0.8)',
                }"
              >
                {{ msg.sender_type === 'user' ? '我' : '知者' }}
              </div>
              <div
                class="font-dialogue"
                style="font-size:14px;line-height:1.8;color:rgba(240,240,255,0.85);"
              >{{ msg.content }}</div>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.backlog-slide-enter-from .galgame-panel { transform: translateX(100%); }
.backlog-slide-enter-active .galgame-panel { transition: transform 0.3s ease-out; }
.backlog-slide-leave-to .galgame-panel { transform: translateX(100%); }
.backlog-slide-leave-active .galgame-panel { transition: transform 0.25s ease-in; }
</style>

// src__figma/app/components/BacklogPanel.tsx
import { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import { Message } from '../data/mockData';

interface BacklogPanelProps {
  messages: Message[];
  isOpen: boolean;
  onClose: () => void;
}

export function BacklogPanel({ messages, isOpen, onClose }: BacklogPanelProps) {
  // 两阶段状态：控制 overlay 可见性 + 面板滑入/滑出
  const [visible, setVisible] = useState(false);
  const [animClass, setAnimClass] = useState('');

  useEffect(() => {
    if (isOpen) {
      setVisible(true);
      // 给浏览器一帧让 DOM 挂载，再加滑入 class
      requestAnimationFrame(() => setAnimClass('slide-enter'));
    } else {
      setAnimClass('slide-exit');
      const t = setTimeout(() => {
        setVisible(false);
        setAnimClass('');
      }, 260);
      return () => clearTimeout(t);
    }
  }, [isOpen]);

  if (!visible) return null;

  return (
    <>
      {/* 暗幕 — .backlog-overlay 供 E2E 选择器使用 */}
      <div
        className="backlog-overlay"
        onClick={onClose}
        style={{ animation: isOpen ? 'fadeIn 0.2s ease' : undefined }}
      />

      {/* 侧栏 — .backlog-panel 供 E2E 选择器使用；transform-only 动画 */}
      <div className={`backlog-panel galgame-panel ${animClass}`}>
        {/* Header */}
        <div
          className="flex items-center justify-between font-ui flex-shrink-0"
          style={{
            padding: '14px 18px',
            borderBottom: '1px solid rgba(255,215,0,0.15)',
          }}
        >
          <div className="flex items-center gap-2">
            <span style={{ color: '#ffd700', fontSize: 13, letterSpacing: 3 }}>📖 回 忆 录</span>
          </div>
          <button
            onClick={onClose}
            style={{ color: 'rgba(255,255,255,0.45)', cursor: 'pointer', lineHeight: 1 }}
          >
            <X size={15} />
          </button>
        </div>

        {/* Messages */}
        <div
          className="flex-1 overflow-y-auto galgame-scrollbar"
          style={{ padding: '12px 0' }}
        >
          {messages.length === 0 ? (
            <div
              className="font-ui"
              style={{ color: 'rgba(255,255,255,0.3)', fontSize: 13, textAlign: 'center', marginTop: 40 }}
            >
              尚无对话记录
            </div>
          ) : (
            <div className="flex flex-col gap-1">
              {messages.map((msg) => {
                const isSage = msg.speakerType === 'sage';
                return (
                  <div
                    key={msg.id}
                    className={isSage ? 'backlog-entry-teacher' : 'backlog-entry-traveler'}
                  >
                    <div
                      className="font-ui"
                      style={{
                        fontSize: 10,
                        color: isSage ? 'rgba(255,215,0,0.75)' : 'rgba(96,165,250,0.75)',
                        letterSpacing: 1,
                        marginBottom: 4,
                      }}
                    >
                      {msg.speakerName}
                      {msg.emotion && (
                        <span style={{ color: 'rgba(255,255,255,0.28)', marginLeft: 6 }}>
                          · {msg.emotion}
                        </span>
                      )}
                      <span style={{ color: 'rgba(255,255,255,0.18)', marginLeft: 6 }}>
                        {msg.timestamp}
                      </span>
                    </div>
                    <p
                      className="font-dialogue"
                      style={{
                        fontSize: 14,
                        lineHeight: 1.75,
                        color: isSage
                          ? 'rgba(240,240,255,0.88)'
                          : 'rgba(180,210,255,0.85)',
                        whiteSpace: 'pre-wrap',
                      }}
                    >
                      {msg.text}
                    </p>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Footer */}
        <div
          className="font-ui flex-shrink-0"
          style={{
            padding: '8px 16px',
            borderTop: '1px solid rgba(255,255,255,0.06)',
            color: 'rgba(255,255,255,0.22)',
            fontSize: 11,
            textAlign: 'center',
          }}
        >
          点击左侧空白处关闭
        </div>
      </div>
    </>
  );
}
