// frontend/src/components/KnowledgeGraphModal.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import type { KnowledgeNode, KnowledgeGraph } from '@/types'

const props = defineProps<{
  isOpen: boolean
  worldName: string
  graph: KnowledgeGraph
}>()

const emit = defineEmits<{ (e: 'close'): void }>()

const selectedNode = ref<KnowledgeNode | null>(null)

const SVG_W = 800, SVG_H = 460

// Layout: simple force-free positioning — use x/y from backend or fallback grid
const nodes = computed(() => {
  return props.graph.nodes.map((n, i) => ({
    ...n,
    cx: n.x ?? 80 + (i % 6) * 120,
    cy: n.y ?? 80 + Math.floor(i / 6) * 100,
  }))
})

const edges = computed(() => props.graph.edges)

function nodeColor(n: KnowledgeNode) {
  if (n.type === 'misconception') return '#ef4444'
  if (n.mastery >= 0.65) return '#4adf6a'
  if (n.mastery >= 0.40) return '#ffd700'
  if (n.mastery >= 0.20) return '#f97316'
  return '#94a3b8'
}

function nodeLabel(n: KnowledgeNode) {
  if (n.type === 'misconception') return '[!] 误解'
  if (n.mastery >= 0.65) return '已掌握'
  if (n.mastery >= 0.40) return '学习中'
  if (n.mastery >= 0.20) return '初识'
  return '未接触'
}

function getEdgePoints(edge: { source: string; target: string }) {
  const src = nodes.value.find(n => n.id === edge.source)
  const tgt = nodes.value.find(n => n.id === edge.target)
  if (!src || !tgt) return null
  return { x1: src.cx, y1: src.cy, x2: tgt.cx, y2: tgt.cy }
}
</script>

<template>
  <Teleport to="body">
    <Transition name="panel-in">
      <div
        v-if="isOpen"
        class="fixed inset-0 z-40 flex items-center justify-center"
        style="background:rgba(0,0,0,0.75);"
        @click="emit('close')"
      >
        <div
          class="galgame-panel flex flex-col"
          style="width:860px;max-width:95vw;max-height:90vh;border-radius:16px;overflow:hidden;"
          @click.stop
        >
          <!-- Header -->
          <div
            class="flex items-center justify-between font-ui flex-shrink-0"
            style="padding:14px 20px;border-bottom:1px solid rgba(255,215,0,0.15);"
          >
            <div>
              <span style="color:#ffd700;font-size:15px;letter-spacing:2px;"> 知识网络</span>
              <span style="color:rgba(255,255,255,0.4);font-size:12px;margin-left:10px;">— {{ worldName }}</span>
            </div>
            <button style="color:rgba(255,255,255,0.5);cursor:pointer;" @click="emit('close')">
              
            </button>
          </div>

          <!-- Body -->
          <div class="flex flex-1 overflow-hidden">
            <!-- SVG Graph -->
            <div class="flex-1 overflow-auto" style="padding:20px;">
              <template v-if="nodes.length === 0">
                <div style="color:rgba(255,255,255,0.3);text-align:center;margin-top:60px;">
                  暂无知识节点
                </div>
              </template>
              <svg
                v-else
                :width="SVG_W" :height="SVG_H"
                style="max-width:100%;"
              >
                <!-- Edges -->
                <g v-for="(edge, i) in edges" :key="i">
                  <template v-if="getEdgePoints(edge)">
                    <line
                      :x1="getEdgePoints(edge)!.x1"
                      :y1="getEdgePoints(edge)!.y1"
                      :x2="getEdgePoints(edge)!.x2"
                      :y2="getEdgePoints(edge)!.y2"
                      stroke="rgba(255,215,0,0.3)"
                      stroke-width="1"
                    />
                    <text
                      :x="(getEdgePoints(edge)!.x1 + getEdgePoints(edge)!.x2) / 2"
                      :y="(getEdgePoints(edge)!.y1 + getEdgePoints(edge)!.y2) / 2 - 4"
                      fill="rgba(255,255,255,0.3)"
                      font-size="9"
                      text-anchor="middle"
                      font-family="'Noto Sans SC', sans-serif"
                    >{{ edge.type }}</text>
                  </template>
                </g>

                <!-- Nodes -->
                <g
                  v-for="node in nodes"
                  :key="node.id"
                  style="cursor:pointer;"
                  @click="selectedNode = selectedNode?.id === node.id ? null : node"
                >
                  <circle
                    :cx="node.cx" :cy="node.cy"
                    :r="selectedNode?.id === node.id ? 14 : 10"
                    :fill="nodeColor(node)"
                    :fill-opacity="0.85"
                    :stroke="selectedNode?.id === node.id ? '#ffd700' : 'rgba(255,255,255,0.2)'"
                    :stroke-width="selectedNode?.id === node.id ? 2 : 1"
                    style="transition:all 0.2s ease;"
                  />
                  <text
                    :x="node.cx" :y="node.cy + 24"
                    fill="rgba(255,255,255,0.8)"
                    font-size="11"
                    text-anchor="middle"
                    font-family="'Noto Sans SC', sans-serif"
                  >{{ node.name }}</text>
                </g>
              </svg>
            </div>

            <!-- Node detail panel -->
            <Transition name="detail-slide">
              <div
                v-if="selectedNode"
                class="galgame-scrollbar"
                style="
                  width:200px;flex-shrink:0;
                  border-left:1px solid rgba(255,215,0,0.15);
                  padding:20px 16px;overflow-y:auto;
                "
              >
                <div class="font-ui" style="color:#ffd700;font-size:14px;margin-bottom:12px;">
                  {{ selectedNode.name }}
                </div>
                <div class="flex flex-col gap-2">
                  <div style="font-size:11px;color:rgba(255,255,255,0.5);">类型</div>
                  <div style="font-size:13px;color:rgba(255,255,255,0.85);">
                    {{ selectedNode.type }}
                  </div>
                  <div style="font-size:11px;color:rgba(255,255,255,0.5);margin-top:8px;">状态</div>
                  <div :style="{ fontSize:'13px', color: nodeColor(selectedNode) }">
                    {{ nodeLabel(selectedNode) }}
                  </div>
                  <div style="font-size:11px;color:rgba(255,255,255,0.5);margin-top:8px;">掌握度</div>
                  <div style="height:4px;background:rgba(255,255,255,0.1);border-radius:2px;overflow:hidden;">
                    <div
                      :style="{
                        height: '100%',
                        width: `${Math.round(selectedNode.mastery * 100)}%`,
                        background: nodeColor(selectedNode),
                      }"
                    />
                  </div>
                  <div style="font-size:12px;color:rgba(255,255,255,0.6);">
                    {{ Math.round(selectedNode.mastery * 100) }}%
                  </div>
                </div>
              </div>
            </Transition>
          </div>

          <!-- Legend -->
          <div
            class="flex items-center gap-6 flex-shrink-0 font-ui"
            style="padding:12px 20px;border-top:1px solid rgba(255,215,0,0.1);font-size:11px;"
          >
            <span v-for="([label, color]) in [
              ['已掌握','#4adf6a'],['学习中','#ffd700'],
              ['初识','#f97316'],['未接触','#94a3b8'],['误解','#ef4444'],
            ]" :key="label" class="flex items-center gap-1">
              <span :style="{ display:'inline-block',width:'8px',height:'8px',borderRadius:'50%',background: color }" />
              <span style="color:rgba(255,255,255,0.6);">{{ label }}</span>
            </span>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.panel-in-enter-from { opacity: 0; transform: scale(0.96) translateY(8px); }
.panel-in-enter-active { transition: opacity 0.3s ease-out, transform 0.3s ease-out; }
.panel-in-leave-to { opacity: 0; }
.panel-in-leave-active { transition: opacity 0.2s ease-in; }
.detail-slide-enter-from { opacity: 0; transform: translateX(20px); }
.detail-slide-enter-active { transition: opacity 0.2s ease, transform 0.2s ease; }
.detail-slide-leave-to { opacity: 0; transform: translateX(20px); }
.detail-slide-leave-active { transition: opacity 0.15s ease; }
</style>

// src__figma/app/components/KnowledgeGraphModal.tsx
import { useState } from 'react';
import { X } from 'lucide-react';
import { KNOWLEDGE_GRAPH, KnowledgeNode } from '../data/mockData';

interface KnowledgeGraphModalProps {
  isOpen: boolean;
  onClose: () => void;
  worldName: string;
}

const MASTERY_COLOR = (mastery: number, type: string) => {
  if (type === 'misconception') return '#ef4444';
  if (mastery >= 0.65) return '#4adf6a';
  if (mastery >= 0.40) return '#ffd700';
  if (mastery >= 0.20) return '#f97316';
  return '#94a3b8';
};

const MASTERY_LABEL = (mastery: number, type: string) => {
  if (type === 'misconception') return '⚠ 误解';
  if (mastery >= 0.65) return '已掌握';
  if (mastery >= 0.40) return '学习中';
  if (mastery >= 0.20) return '初识';
  return '未接触';
};

export function KnowledgeGraphModal({ isOpen, onClose, worldName }: KnowledgeGraphModalProps) {
  const [selectedNode, setSelectedNode] = useState<KnowledgeNode | null>(null);

  if (!isOpen) return null;

  const { nodes, edges } = KNOWLEDGE_GRAPH;
  const svgW = 800, svgH = 460;

  return (
    <div className="absolute inset-0 z-40 flex items-center justify-center" style={{ background: 'rgba(0,0,0,0.75)' }}>
      <div
        className="galgame-panel flex flex-col"
        style={{
          width: 860, maxWidth: '95vw',
          maxHeight: '90vh',
          borderRadius: 16,
          animation: 'panelIn 0.3s ease-out',
          overflow: 'hidden',
        }}
      >
        {/* Header */}
        <div
          className="flex items-center justify-between font-ui flex-shrink-0"
          style={{ padding: '14px 20px', borderBottom: '1px solid rgba(255,215,0,0.15)' }}
        >
          <div>
            <span style={{ color: '#ffd700', fontSize: 15, letterSpacing: 2 }}>📊 知识网络</span>
            <span style={{ color: 'rgba(255,255,255,0.4)', fontSize: 12, marginLeft: 10 }}>— {worldName}</span>
          </div>
          <button onClick={onClose} style={{ color: 'rgba(255,255,255,0.5)', cursor: 'pointer' }}>
            <X size={18} />
          </button>
        </div>

        {/* Body */}
        <div className="flex flex-1 overflow-hidden">
          {/* SVG Graph */}
          <div className="flex-1 relative overflow-hidden" style={{ minHeight: 300 }}>
            <svg
              width="100%" height="100%"
              viewBox={`0 0 ${svgW} ${svgH}`}
              style={{ display: 'block' }}
            >
              {/* Background */}
              <rect width={svgW} height={svgH} fill="transparent" />

              {/* Edges */}
              {edges.map((edge, i) => {
                const src = nodes.find(n => n.id === edge.source);
                const tgt = nodes.find(n => n.id === edge.target);
                if (!src || !tgt) return null;
                const midX = (src.x + tgt.x) / 2;
                const midY = (src.y + tgt.y) / 2;
                const isMisconception = src.type === 'misconception' || tgt.type === 'misconception';
                return (
                  <g key={i}>
                    <line
                      x1={src.x} y1={src.y} x2={tgt.x} y2={tgt.y}
                      stroke={isMisconception ? 'rgba(239,68,68,0.4)' : 'rgba(255,215,0,0.18)'}
                      strokeWidth={isMisconception ? 1 : 1.5}
                      strokeDasharray={isMisconception ? '4 3' : undefined}
                    />
                    {/* Edge label */}
                    <text
                      x={midX} y={midY - 4}
                      fill="rgba(255,255,255,0.3)"
                      fontSize={9}
                      textAnchor="middle"
                      fontFamily="Noto Sans SC, sans-serif"
                    >
                      {edge.label}
                    </text>
                  </g>
                );
              })}

              {/* Nodes */}
              {nodes.map((node) => {
                const r = 14 + node.mastery * 14;
                const color = MASTERY_COLOR(node.mastery, node.type);
                const isSelected = selectedNode?.id === node.id;
                return (
                  <g
                    key={node.id}
                    onClick={() => setSelectedNode(isSelected ? null : node)}
                    style={{ cursor: 'pointer' }}
                  >
                    {/* Glow ring */}
                    <circle
                      cx={node.x} cy={node.y} r={r + 6}
                      fill="none"
                      stroke={color}
                      strokeWidth={isSelected ? 2 : 0.5}
                      opacity={isSelected ? 0.8 : 0.25}
                    />
                    {/* Main circle */}
                    <circle
                      cx={node.x} cy={node.y} r={r}
                      fill={`${color}22`}
                      stroke={color}
                      strokeWidth={isSelected ? 2.5 : 1.5}
                    />
                    {/* Mastery fill */}
                    <circle
                      cx={node.x} cy={node.y} r={r * node.mastery}
                      fill={`${color}35`}
                    />
                    {/* Label */}
                    <text
                      x={node.x} y={node.y + r + 16}
                      fill={isSelected ? color : 'rgba(255,255,255,0.75)'}
                      fontSize={11}
                      textAnchor="middle"
                      fontFamily="Noto Sans SC, sans-serif"
                      fontWeight={isSelected ? 600 : 400}
                    >
                      {node.name}
                    </text>
                    {/* Mastery % */}
                    {node.mastery > 0 && (
                      <text
                        x={node.x} y={node.y + 4}
                        fill={color}
                        fontSize={10}
                        textAnchor="middle"
                        fontFamily="Noto Sans SC, sans-serif"
                        fontWeight={600}
                      >
                        {Math.round(node.mastery * 100)}%
                      </text>
                    )}
                  </g>
                );
              })}
            </svg>
          </div>

          {/* Side info panel */}
          <div
            className="flex-shrink-0 galgame-scrollbar overflow-y-auto"
            style={{ width: 200, borderLeft: '1px solid rgba(255,215,0,0.12)', padding: '14px 14px' }}
          >
            {selectedNode ? (
              <div className="galgame-fade-in">
                <div
                  className="font-ui"
                  style={{ color: MASTERY_COLOR(selectedNode.mastery, selectedNode.type), fontSize: 14, fontWeight: 600, marginBottom: 6 }}
                >
                  {selectedNode.name}
                </div>
                <div className="font-ui" style={{ color: 'rgba(255,255,255,0.4)', fontSize: 11, marginBottom: 10 }}>
                  {MASTERY_LABEL(selectedNode.mastery, selectedNode.type)}
                </div>
                <div style={{ height: 1, background: 'rgba(255,255,255,0.08)', marginBottom: 10 }} />
                {selectedNode.bloomLevel && (
                  <div className="font-ui" style={{ fontSize: 11, color: 'rgba(255,255,255,0.45)', marginBottom: 4 }}>
                    认知层级：{selectedNode.bloomLevel}
                  </div>
                )}
                <div
                  style={{
                    height: 6, borderRadius: 3,
                    background: 'rgba(255,255,255,0.1)',
                    overflow: 'hidden', marginBottom: 4,
                  }}
                >
                  <div
                    style={{
                      height: '100%',
                      width: `${selectedNode.mastery * 100}%`,
                      background: MASTERY_COLOR(selectedNode.mastery, selectedNode.type),
                      borderRadius: 3,
                    }}
                  />
                </div>
                <div className="font-ui" style={{ fontSize: 11, color: 'rgba(255,255,255,0.3)' }}>
                  掌握度 {Math.round(selectedNode.mastery * 100)}%
                </div>
              </div>
            ) : (
              <div className="font-ui" style={{ color: 'rgba(255,255,255,0.25)', fontSize: 12, marginTop: 20 }}>
                点击节点查看详情
              </div>
            )}

            <div style={{ marginTop: 20 }}>
              <div className="font-ui" style={{ color: 'rgba(255,255,255,0.35)', fontSize: 11, marginBottom: 8 }}>图例</div>
              {[
                { color: '#4adf6a', label: '已掌握 ≥65%' },
                { color: '#ffd700', label: '学习中 40-65%' },
                { color: '#f97316', label: '初识 20-40%' },
                { color: '#94a3b8', label: '未接触' },
                { color: '#ef4444', label: '⚠ 误解' },
              ].map((item) => (
                <div key={item.color} className="flex items-center gap-2 mb-1.5">
                  <div style={{ width: 8, height: 8, borderRadius: '50%', background: item.color, flexShrink: 0 }} />
                  <span className="font-ui" style={{ fontSize: 10, color: 'rgba(255,255,255,0.4)' }}>
                    {item.label}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
